config/routes.rb
Rails.application.routes.draw do
  resources :goals
 
  root "visits#index"
  
  resources :visits
 
 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/models/visit.rb
class Visit < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

    def index
        @visits = Visit.all #visits listed in desc order
    end

    def new
        @visit = Visit.new 
    end

    def create
        @visit = Visit.create(visit_params)
        if @visit.save
            redirect_to visits_path(@visit)
        else
            render :new       
        end
    end

#    def update 
#        if @visit.update(visit_params)
#            redirect_to visit_path(@visit)           
#       else
#           render :edit
#       end
#    end

    def show
        @visit = Visit.find(params[:id])
    end

    def destroy
        Visit.find(params[:id]).destroy
        redirect_to visits_path
    end

    private

    def visit_params
        params.require(:visit).permit(:goal_name, :short_term, :long_term, :word, :plus, :minus, :iwp, :prompt_type, :prompt_level, :error, :error_notes, :comments)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sidekicktherapy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visits/index.html.erb
<h1>Patient POC</h1>

<h3><%= link_to "New Visit Note", new_visit_path(@visit) %></h3>


<ul>
    <% @visits.each do |v| %>
        <li>
            <%= link_to v.goal_name, visit_path(v) %>
        </li>
    <% end %>
</ul>

app/views/visits/new.html.erb
<h1>New Form</h1>


<%= form_for(@visit) do |f| %>

<%# 
 Goal needs to be its own model. 
 When goals are created, they get added to a collection. 
 Goals becomes a collection select and or can create a new goal 
 drop down collection_select here of pre-made goal templates %>

<h2>Goal: <%= f.text_field :goal_name %> <strong></h2> Short term: <%= f.check_box :short_term %> Long term: <%= f.check_box :long_term %></strong>
<br><br>

<%# 
 Stetch goal: List of words can also be its own template with option to add a word 

 The value of a " + " checkbox return a point value 
 A " - " checked box has zero value 
 IWP adds a negative value to diminish from the " + " point value 

 Prompt level can max to 5 each awarding a point value. n/a = positive value point 
 Marked error checkboxes have negative values to subtract from total score 

 The goal is keep the checked boxes marking only " + " and "n/a" 
 A bracket of scores render a color to mark levels of achievement / passing goals 
 The color of the Goals object changes color to reflect progress %>

    <h2>Word: <%= f.text_field :word %></h2>

    <strong>First attempt:</strong> + <%= f.check_box :plus %>  - <%= f.check_box :minus %> || IWP <%= f.check_box :iwp %>
    <strong>Second attempt:</strong>  + <%= f.check_box :plus %>  - <%= f.check_box :minus %> || IWP <%= f.check_box :iwp %>
    <strong>Third attempt:</strong>  + <%= f.check_box :plus %>  - <%= f.check_box :minus %> || IWP <%= f.check_box :iwp %>
    <strong>Fourth attempt:</strong>  + <%= f.check_box :plus %>  - <%= f.check_box :minus %> || IWP <%= f.check_box :iwp %>
    <strong>Fifth attempt:</strong> + <%= f.check_box :plus %>  - <%= f.check_box :minus %> || IWP <%= f.check_box :iwp %>
    
    <br>Prompt type: [collection select menu here]
    
    <br>Prompt level: <strong>1 <%= f.check_box :prompt_level %> 2 <%= f.check_box :prompt_level %> 3 <%= f.check_box :prompt_level %></strong>
    
    <br>Where errors started: <strong>beginning <%= f.check_box :error %>middle <%= f.check_box :error %> end <%= f.check_box :error %></strong>
    
    <%# Hypothetical highest achieved value %>
    <br><br>Score: ___ / 50

    <br><br><strong>Further notes on errors:</strong>
    <br><%= f.text_area :error_notes, cols:40, rows:3 %>
    <br><br><br>
    
    <%# option to add a field for more words %>
    
    <strong>Notes about visit:</strong>
    <br>
    <%= f.text_area :comments, cols:50, rows:4 %>
    <br>
    <br>
    <%= f.submit %>

<% end %>

<br><br>
<a href="/">Back to Index</a>

app/views/visits/show.html.erb
<h1>
    <%= @visit.goal_name %>
</h1>
<small>created at:</small> <%= @visit.created_at %><br>
<small>short term:</small> <%= @visit.short_term %><br>
<small>long term:</small> <%= @visit.long_term %>
<br><br>

<h2>
    <%= @visit.word %>
</h2>
Errors started: <%= @visit.error %><br><br>

Notes on errors made: <b><%= @visit.error_notes %></b><br><br>

Additional comments on visit: <b><%= @visit.comments %><br><br></b>
<br><br>
<br><br>
<br><br>
<a href="/">Back to Index</a>